# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.daemon = false
fabric.loom.ignoreDependencyLoomVersionValidation = true
fabric.loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false

# Project
mod_id = amendments
mod_name = Amendments
mod_author = MehVahdJukaar, Plantkillable
mod_description = Many tweaks to Vanilla Blocks
mod_version=1.21-2.1.8
mod_license = Supplementaries Team License v.1.5
mod_authors = MehVahdJukaar, Plantkillable
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/amendments
mod_credits = MehVahdJukaar
mod_github = https://github.com/MehVahdJukaar/amendments

release_type = release
maven_group = net.mehvahdjukaar

mc_version = 1.21.1
minecraft_min_version = 1.21
neoforge_version=21.1.235

fabric_loader_version = 0.17.2
fabric_api_version = 0.116.6+1.21.1

parchment_mappings_version = 2024.11.17

# Publishing
repository = mehvahdjukaar/amendments
modrinth_project_id = amendments
curseforge_project_id = 896746

# Other deps
moonlight_version=1.21.1-3.3.4
codecui_version=1.21.1-1.4.0

moonlight_min_version=1.21-3.1.0c
suppsquared_version = 1.21-1.2.12
supplementaries_version = 1.21-3.4.18
create_version = 0.5.1-f-build.1335
registrate_version = 1.1.42
flywheel_version = 1.20.1-0.6.10-7
cca_version = 5.2.1
soul_fire_d_version = 6.0.0
